# Generated by Django 5.0 on 2023-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('data_criacao', models.DateField()),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
